CREATE TABLE accounts (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    credit DEC(15,2) NOT NULL,
	currency VARCHAR(100) NOT NULL,
    PRIMARY KEY(id)
);
INSERT INTO accounts(name, credit, currency)
VALUES('Bob', 10000, "dollar");
INSERT INTO accounts(name, credit, currency)
VALUES('Tom', 10000, "dollar");
INSERT INTO accounts(name, credit, currency)
VALUES('Sad', 10000, "dollar");

BEGIN;
UPDATE accounts 
SET credit = credit - 500
WHERE id = 1;

UPDATE accounts
SET credit = credit + 500
WHERE id = 2; 

UPDATE accounts 
SET credit = credit + 700
WHERE id = 1;

UPDATE accounts
SET credit = credit - 700
WHERE id = 2; 

UPDATE accounts 
SET credit = credit - 100
WHERE id = 2;

UPDATE accounts
SET credit = credit + 100
WHERE id = 3; 

SELECT id, name, credit, currency
FROM accounts;

ROLLBACK;

COMMIT;

